name: 'Buildkite Pipeline'
description: 'Trigger a Buildkite pipeline'
inputs:
  access_token:
    description: 'A Buildkite access token which must have the `write_builds` permission, and if you want to wait for the builds to complete also needs the `read_builds` permission.'
    required: true
  pipeline:
    description: 'Name of the pipeline to trigger, in the format `organization/pipeline.'
    required: true
  branch:
    description: 'Name of the branch to build.'
    required: true
    default: ''
  commit:
    description: 'The commit to build.'
    required: true
    default: ''
  message:
    description: 'The message to associate with the build.'
    required: false
    default: ':github: Triggered by GitHub Action'
  env:
    description: 'Environment variables to pass to the Buildkite build in JSON format.'
    required: false
  async:
    description: 'If true then the action does not wait for the build to complete.'
    required: false
outputs:
  id:
    description: 'The identifier of the build.'
  number:
    description: 'The build number.'
  url:
    description: 'The API URL of the build.'
  web_url:
    description: 'The web URL of the build.'
  state:
    description: 'The state of the build.'
  data:
    description: 'The raw data about the build in JSON format.'
runs:
  using: 'docker'
  image: 'Dockerfile'
