name: buildkite-pipeline
on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Trigger pipeline
      id: run
      uses: ./
      with:
        access_token: fake_access_token
        pipeline: example-org/example-pipeline
        branch: example-branch
        env: '{"TARGET":"QA"}'
      env:
        TEST_MODE: true
    - name: Report build status
      run: echo "Build ${{ steps.run.outputs.id }} ${{ steps.run.outputs.state }}"
